### ISSUE TITLE
Shallow cloning

### ISSUE THREAD

**Issue by connieksun** [buoyant-data/oxbow#25]
Hi, is shallow cloning supported? Is there an easy way to add support for this if not?

**Comment by rtyler** [comment]
:wave: Can you share more about what you're looking for with shallow clones? Shallow clones are basically copies of a transaction log while pointing to the original delta table's data files. That's why I'm not entirely sure what you're looking for here  :smile:

**Comment by connieksun** [comment]
Yes, sorry, what I mean is: I believe the current implementation creates a delta table that duplicates the data files stored in S3. It would be nice to just have the transaction log without the overhead of copying the data (reference: [migrate parquet data with clone parquet](https://docs.databricks.com/en/migration/parquet-to-delta-lake.html#migrate-parquet-data-with-clone-parquet))

**Comment by rtyler** [comment]
Both actually function similar to a shallow clone insofar that they're not copying the parquet data from one location to another ,but rather they're creating a transaction log with URL references to pre-existing data files

**Comment by connieksun** [comment]
Oh I see, I misunderstood. Thank you! Is there a way to specify where to put the delta table (in a location separate from where the parquet files are stored)?

**Comment by rtyler** [comment]
There is not currently a mechanism to do that. oxbow puts the delta log files adjacent to the parquet files to ensure consistent behavior when oxbow is triggered for files in different object store prefixes

**Comment by connieksun** [comment]
Gotcha, is there a way you would recommend implementing this functionality?
