### ISSUE TITLE
Errors creating checkpoints

### ISSUE THREAD

**Issue by connieksun** [buoyant-data/oxbow#27]
Hello again! We were running oxbow for a few weeks and ran into an issue where checkpoints couldn't be created. Guessing this is due to the table version updating in-between writing and creating the checkpoint because we kept receiving this message: "The table was reloaded to create a checkpoint but a new version already exists!" (line 57 of `crates/oxbow/src/write.rs`). Eventually, because no checkpoints could be created, opening the table took longer and longer, until the lambda would continuously time out...

Is the table version changing due to lambda concurrency? Any suggestions for how to resolve? Thank you!

**Comment by rtyler** [comment]
@connieksun I believe I fixed that issue in some debugging I was doing yesterday! Release 1.0.7 is being released right now which I think might address your concerns, please give it a try.

**Comment by connieksun** [comment]
Looks like it's working, thank you!
